version: 2

sources:
  - name: northwind
    database: northwind_dw
    schema: public
    tables:
      - name: orders
      - name: order_details
      - name: products
      - name: customers
      - name: categories
      - name: employees